# JVM ?? - ???????
org.gradle.jvmargs=-Xmx32g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g

# ??????
org.gradle.parallel=true

# ??????
org.gradle.caching=true

# ???????????????
org.gradle.configuration-cache=true

# ????
org.gradle.configureondemand=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true